### ISSUE TITLE
The closest model (M1) to the input has: {'feh': -0.25}, but a closer match (M2) was found in the MADYS database: {'feh': 0.0, 'afe': 0.0, 'v_vcrit': 0.0, 'fspot': 0.0, 'B': 0, 'he': 0.27}.

### ISSUE THREAD

**Issue by YxmMu** [vsquicciarini/alpha-ubbi#3]
Hi! I'm glad you can add more models, but I seem to have encountered new problems...
I only downloaded  parsec_m0.25 model. When I set feh=-0.25, it shows that the best model is feh=0.00, not feh=-0.25. When I choose “N”, it will directly lead to failure to run.
Do I have to change other parameters so that it uses the parsec_m0.25 model instead of the parsec_p0.00 model?

`els_file='/home/yang/Madys/els.txt'
els_obj=madys.SampleObject(els_file,id_type='DR3',verbose=0,ext_map='leike',feh=-0.25)
result=els_obj.get_params('parsec',age_range=[1,400],n_try=200)`

`The closest model (M1) to the input has: {'feh': -0.25}, but a closer match (M2) was found in the MADYS database:
{'feh': 0.0, 'afe': 0.0, 'v_vcrit': 0.0, 'fspot': 0.0, 'B': 0, 'he': 0.27}.
Do you want me to download this model? Press 'N' to use M1 instead. [Y/N]:N

ValueError: Model parsec_p0.00 not found. Are you sure it is in your search path?`

**Comment by vsquicciarini** [comment]
Hi! The problem lies in the fact that the keyword 'feh' should be provided not during inizialization (i.e. in SampleObject()), but rather in get_params(). I hope that helps!

**Comment by YxmMu** [comment]
Thank you !
Although it will still prompt that the model with feh=0.0 is better, the code is working now.
`els_file='/home/yang/Madys/els.txt'
els_obj=madys.SampleObject(els_file,id_type='DR3',verbose=0,ext_map='leike')
result=els_obj.get_params('parsec',age_range=[1,400],n_try=200,feh=-0.25)`

`The closest model (M1) to the input has: {'feh': -0.25}, but a closer match (M2) was found in the MADYS database:
{'feh': 0.0, 'afe': 0.0, 'v_vcrit': 0.0, 'fspot': 0.0, 'B': 0, 'he': 0.27}.
Do you want me to download this model? Press 'N' to use M1 instead. [Y/N]:N`
`Program running. Done: 41/73 (56.2%). Estimated time left: 48 s.
Execution ended. Elapsed time: 101 s.`

Thanks again :)

**Comment by vsquicciarini** [comment]
You are welcome, I hope that you are finding our tool useful! :)
Btw, I've fixed the bug of the wrong message, now it should disappear. Thank you for noticing it!
