### ISSUE TITLE
[Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by kilibo** [vsquicciarini/alpha-ubbi#4]
When I tested your program, I found it could not run.
For a small sample size, it can run smoothly,such as
`
star_list=['Gaia DR3 537529798644191232','Gaia DR3 1087909890317863040', 'Gaia DR3 5836041389104329216', 'Gaia DR3 987536165308035328', 'Gaia DR3 4225093954826903680']`
`p2=madys.SampleObject(star_list,id_type='DR3',ext_map=None)`
`p2.phot_table`
![2022-07-10 18-44-28 的屏幕截图](https://user-images.githubusercontent.com/109021036/178141614-df418cce-1f32-43e6-a744-3ac339f80691.png)

but for a large sample size, it cannot obtain data，such as
`f='1000stars.csv' #1000 random stars`
`p1=madys.SampleObject(f,id_type='DR3',ext_map='leike',verbose=0) #collects data `
`p1.phot_table`

`ConnectionResetError: [Errno 104] Connection reset by peer`

`During handling of the above exception, another exception occurred:
ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))`

Is it because the sample size is too large to refuse data query, or is it because of my network?

**Comment by vsquicciarini** [comment]
Hello, I can ensure that usually there are no problems even with queries containing 10^5 stars.
Since I am experiencing similar problems right now, I believe it has to do with Gaia servers (very strange, actually: I've never stumbled across anything similar before).
I'll keep on trying to execute the query, and keep you updated.

**Comment by kilibo** [comment]
I also think it is the problem of Gaia servers.
I wish this problem can be solved quickly, and I will always pay attention to the update ：）

**Comment by vsquicciarini** [comment]
Thank you so much! Confirming what we were saying, I've just noticed that accessing https://tapvizier.u-strasbg.fr// returns a 503 error. I hope they fix it soon.

**Comment by vsquicciarini** [comment]
Hi! The tapvizier server is working now, and on my PC the query runs smoothly. Does it work for you now?

**Comment by kilibo** [comment]
yeah！I just tested it, It's working now.
Thanks a lot!  :)

**Comment by vsquicciarini** [comment]
Great! Thanks for informing me about the problem :) I'll add a connection check before the query to return an explicit message, should it happen again.
